--
-- Table DDL : KijijiAds
--
CREATE OR REPLACE TABLE KijijiAds
(
    ADID INTEGER NOT NULL,
    ADURL VARCHAR(500) NOT NULL,
    ADCATEGORY VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    PUBDATE VARCHAR(100) NOT NULL,
    PRICE FLOAT NOT NULL,
    LAST_UPDATE DATETIME
)
CLUSTER BY (
  LOCATION ,ADCATEGORY
);